server {
	server_name 16-171-151-132.nip.io;
	root /var/www/task3-site/html;
	index index.html;

	error_page 404 /404.html;
	error_page 500 502 503 504 /50x.html;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/16-171-151-132.nip.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/16-171-151-132.nip.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = 16-171-151-132.nip.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	listen 80;
	server_name 16-171-151-132.nip.io;
    return 404; # managed by Certbot


}